// Project cover screenshots → public/shots/<id>.webp (1280×800, q80).
//
// Sources come from scripts/shots.config.json: a live URL is captured with the
// locally installed Chrome (puppeteer-core — nothing is downloaded, and this
// never runs as part of `npm run build`); a { file } entry is a local image
// rendered cover-fit into the same frame. Existing files are skipped unless
// --force is passed. Afterwards src/data/shots.ts is regenerated from the
// files that exist, so the site picks the covers up automatically.
//
//   npm run shots            # capture missing covers
//   npm run shots -- --force # re-capture everything
//   npm run shots -- resite  # only these ids
//   CHROME_PATH=/path/to/chrome npm run shots

import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import puppeteer from "puppeteer-core";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../public/shots");
const MANIFEST = resolve(__dirname, "../src/data/shots.ts");
const CONFIG = JSON.parse(readFileSync(resolve(__dirname, "shots.config.json"), "utf8"));

const WIDTH = 1280;
const HEIGHT = 800;
const QUALITY = 80;
const NAV_TIMEOUT = 45_000;
const SETTLE_MS = 1_500;

const argv = process.argv.slice(2);
const force = argv.includes("--force");
const only = argv.filter((a) => !a.startsWith("--"));

function findChrome() {
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH;
  const candidates = [
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  for (const bin of ["google-chrome", "chromium", "chromium-browser"]) {
    try {
      return execSync(`which ${bin}`, { stdio: ["ignore", "pipe", "ignore"] })
        .toString()
        .trim();
    } catch {
      /* try next */
    }
  }
  throw new Error("No Chrome found. Set CHROME_PATH=/path/to/chrome.");
}

/** Best-effort: hide the usual cookie/consent banners before shooting. */
async function dismissBanners(page) {
  await page
    .evaluate(() => {
      const sel = [
        "[id*='cookie']",
        "[class*='cookie']",
        "[id*='consent']",
        "[class*='consent']",
        "[aria-label*='cookie' i]",
      ];
      for (const el of document.querySelectorAll(sel.join(","))) {
        const r = el.getBoundingClientRect();
        if (r.height > 40 && r.width > 200) el.style.display = "none";
      }
    })
    .catch(() => {});
}

async function shootUrl(page, url, out) {
  await page.goto(url, { waitUntil: "networkidle2", timeout: NAV_TIMEOUT });
  await new Promise((r) => setTimeout(r, SETTLE_MS));
  await dismissBanners(page);
  await page.screenshot({ path: out, type: "webp", quality: QUALITY });
}

async function shootFile(page, file, out) {
  if (!existsSync(file)) throw new Error(`file not found: ${file}`);
  const html = join(tmpdir(), `shot-${Date.now()}.html`);
  writeFileSync(
    html,
    `<!doctype html><meta charset="utf-8"><style>html,body{margin:0;background:#0a0a0b}
img{display:block;width:${WIDTH}px;height:${HEIGHT}px;object-fit:cover;object-position:top}</style>
<img src="${pathToFileURL(file).href}">`,
  );
  await page.goto(pathToFileURL(html).href, { waitUntil: "load" });
  await new Promise((r) => setTimeout(r, 300));
  await page.screenshot({ path: out, type: "webp", quality: QUALITY });
}

function writeManifest() {
  const ids = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR)
        .filter((f) => f.endsWith(".webp"))
        .map((f) => f.replace(/\.webp$/, ""))
        .sort()
    : [];
  const body = ids.map((id) => `  ${JSON.stringify(id)},`).join("\n");
  writeFileSync(
    MANIFEST,
    `/**
 * Quest ids that have a screenshot at /public/shots/<id>.webp (${WIDTH}×${HEIGHT}, q${QUALITY}).
 * GENERATED by scripts/capture-shots.mjs (\`npm run shots\`) — do not edit by hand.
 */
export const SHOTS = new Set<string>([
${body}
]);
`,
  );
  console.log(`[shots] manifest: ${ids.length} cover(s) → src/data/shots.ts`);
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const entries = Object.entries(CONFIG).filter(
    ([id]) => !id.startsWith("_") && (only.length === 0 || only.includes(id)),
  );

  const browser = await puppeteer.launch({
    executablePath: findChrome(),
    headless: true,
    args: ["--no-sandbox", "--disable-gpu", "--hide-scrollbars"],
  });

  let ok = 0;
  let skipped = 0;
  let failed = 0;
  try {
    for (const [id, src] of entries) {
      const out = join(OUT_DIR, `${id}.webp`);
      if (!force && existsSync(out)) {
        skipped++;
        continue;
      }
      const page = await browser.newPage();
      await page.setViewport({ width: WIDTH, height: HEIGHT, deviceScaleFactor: 1 });
      await page.emulateMediaFeatures([{ name: "prefers-color-scheme", value: "dark" }]);
      try {
        if (typeof src === "string") await shootUrl(page, src, out);
        else await shootFile(page, src.file, out);
        console.log(`[shots] ✓ ${id}`);
        ok++;
      } catch (err) {
        console.warn(`[shots] ✗ ${id}: ${err.message}`);
        failed++;
      } finally {
        await page.close();
      }
    }
  } finally {
    await browser.close();
  }
  writeManifest();
  console.log(`[shots] done — ${ok} captured, ${skipped} skipped, ${failed} failed`);
}

main().catch((err) => {
  console.error(`[shots] fatal: ${err.message}`);
  process.exit(1);
});
