/**
 * Quest ids that have a screenshot at /public/shots/<id>.webp (1280×800, q80).
 * GENERATED by scripts/capture-shots.mjs (`npm run shots`) — do not edit by hand.
 */
export const SHOTS = new Set<string>([
  "AI-ROUTER",
  "crypto-ai",
  "dividend",
  "indian-ipo",
  "investment",
  "investment-plan",
  "market-news",
  "programmatic-SEO-engine",
  "repo-intelligence",
  "resite",
  "smart-trading",
  "stocksafe-bundles",
  "strategy-backtest",
  "streamverse",
  "typezap",
]);
